### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by madmaxio** [takahirox/wgpu-rust-renderer#28]
@takahirox  Hi, any plans to continue on this project? Also I'm interested in wgpu related consulting with funding, can you be up for this?

**Comment by madmaxio** [comment]
> As there are PRs from me waiting from the end of July, and a bunch of reported issues, I don't think this project is alive anymore.

Do you plan to support a fork?

**Comment by michalusio** [comment]
@madmaxio 
Not really, as I have other projects currently on the table.
I could write a few bugfixes, but I'm not sure what would be the direction to take this project further.

As I see from the PRs, @takahirox has responded, so maybe not all hope is lost?

**Comment by michalusio** [comment]
Update: All hope is actually lost.
